# -*- mode: python ; coding: utf-8 -*-

import sys
import os
from pathlib import Path

# Add the backend source to the path
backend_src = Path(__file__).parent.parent.parent.parent / "backend"
sys.path.insert(0, str(backend_src))

# Get the backend source directory
backend_dir = Path(__file__).parent.parent.parent.parent / "backend"

block_cipher = None

# Collect all Python files from backend
def collect_backend_files():
    """Collect all Python files from the backend directory."""
    files = []
    for root, dirs, filenames in os.walk(backend_dir):
        # Skip __pycache__, .pytest_cache, tests, and other non-source directories
        dirs[:] = [d for d in dirs if d not in ('__pycache__', '.pytest_cache', '.git', 'tests', 'venv', '.venv', 'env', '.env')]
        for f in filenames:
            if f.endswith('.py') or f.endswith('.yaml') or f.endswith('.yml') or f.endswith('.json') or f.endswith('.txt') or f.endswith('.ini') or f.endswith('.cfg'):
                src = os.path.join(root, f)
                dst = os.path.relpath(src, backend_dir)
                files.append((src, dst))
    return files

backend_files = collect_backend_files()

# Hidden imports for PyInstaller
hidden_imports = [
    # FastAPI and Starlette
    'fastapi',
    'fastapi.applications',
    'fastapi.routing',
    'fastapi.middleware',
    'fastapi.middleware.cors',
    'fastapi.responses',
    'fastapi.exceptions',
    'fastapi.params',
    'fastapi.dependencies',
    'fastapi.security',
    'fastapi.openapi',
    'fastapi.openapi.docs',
    'fastapi.openapi.utils',
    'starlette',
    'starlette.applications',
    'starlette.routing',
    'starlette.middleware',
    'starlette.middleware.cors',
    'starlette.responses',
    'starlette.exceptions',
    'starlette.websockets',
    'starlette.staticfiles',
    'starlette.templating',
    'starlette.datastructures',
    'starlette.background',
    'starlette.concurrency',
    'starlette.types',
    'uvicorn',
    'uvicorn.main',
    'uvicorn.config',
    'uvicorn.server',
    'uvicorn.protocols',
    'uvicorn.protocols.http',
    'uvicorn.protocols.websockets',
    'uvicorn.lifespan',
    'uvicorn.supervisors',
    'uvicorn.workers',
    
    # Pydantic
    'pydantic',
    'pydantic.v1',
    'pydantic.v2',
    'pydantic.main',
    'pydantic.fields',
    'pydantic.validators',
    'pydantic.types',
    'pydantic.networks',
    'pydantic.datetime_parse',
    'pydantic.color',
    'pydantic.json_schema',
    'pydantic_core',
    'pydantic_settings',
    
    # SQLAlchemy
    'sqlalchemy',
    'sqlalchemy.ext.asyncio',
    'sqlalchemy.orm',
    'sqlalchemy.engine',
    'sqlalchemy.pool',
    'sqlalchemy.dialects.postgresql',
    'sqlalchemy.dialects.postgresql.asyncpg',
    'asyncpg',
    'psycopg2',
    'psycopg2._psycopg',
    'alembic',
    'alembic.config',
    'alembic.script',
    'alembic.environment',
    'alembic.migration',
    'alembic.operations',
    'alembic.autogenerate',
    
    # Celery and Redis
    'celery',
    'celery.app',
    'celery.worker',
    'celery.canvas',
    'celery.result',
    'celery.schedules',
    'redis',
    'redis.asyncio',
    'redis.connection',
    'redis.client',
    'redis.commands',
    'redis.lock',
    'redis.sentinel',
    'redis.cluster',
    'hiredis',
    
    # YAML and config
    'yaml',
    'yaml.constructor',
    'yaml.resolver',
    'yaml.composer',
    'yaml.parser',
    'yaml.scanner',
    'yaml.emitter',
    'yaml.serializer',
    'yaml.representer',
    'yaml.reader',
    'yaml.writer',
    'yaml.error',
    'yaml.tokens',
    'yaml.events',
    'yaml.nodes',
    'yaml.dumper',
    'yaml.loader',
    'yaml.cyaml',
    'yaml.cyaml',
    
    # Scientific computing
    'numpy',
    'numpy.core',
    'numpy.lib',
    'numpy.linalg',
    'numpy.fft',
    'numpy.random',
    'numpy.polynomial',
    'scipy',
    'scipy.sparse',
    'scipy.linalg',
    'scipy.optimize',
    'scipy.interpolate',
    'scipy.integrate',
    'scipy.stats',
    'scipy.signal',
    'scipy.ndimage',
    'scipy.fft',
    'scipy.special',
    
    # CFD/Mesh libraries
    'meshio',
    'meshio._common',
    'meshio._exceptions',
    'meshio._helpers',
    'meshio.vtk',
    'meshio.xdmf',
    'meshio.gmsh',
    'meshio.med',
    'meshio.abaqus',
    'meshio.ansys',
    'meshio.flac3d',
    'meshio.h5m',
    'meshio.permas',
    'meshio.vtu',
    'meshio.ply',
    'meshio.stl',
    'meshio.obj',
    'meshio.off',
    'meshio.gmsh',
    'meshio._gmsh',
    'pyvista',
    'pyvista.core',
    'pyvista.plotting',
    'pyvista.examples',
    'vtk',
    'vtkmodules',
    'vtkmodules.all',
    'vtkmodules.vtkCommonCore',
    'vtkmodules.vtkCommonDataModel',
    'vtkmodules.vtkFiltersCore',
    'vtkmodules.vtkFiltersGeometry',
    'vtkmodules.vtkIOGeometry',
    'vtkmodules.vtkIOXML',
    'vtkmodules.vtkRenderingCore',
    'vtkmodules.vtkRenderingOpenGL2',
    'vtkmodules.vtkInteractionStyle',
    'vtkmodules.vtkRenderingFreeType',
    'gmsh',
    
    # Data processing
    'pandas',
    'pandas.core',
    'pandas.io',
    'polars',
    'polars.internals',
    
    # Auth and security
    'jose',
    'jose.jwt',
    'jose.exceptions',
    'jose.utils',
    'jose.backends',
    'jose.backends.rsa_backend',
    'passlib',
    'passlib.handlers',
    'passlib.handlers.bcrypt',
    'passlib.context',
    'cryptography',
    'cryptography.hazmat',
    'cryptography.hazmat.primitives',
    'cryptography.hazmat.primitives.asymmetric',
    'cryptography.hazmat.primitives.ciphers',
    'cryptography.hazmat.primitives.hashes',
    'cryptography.hazmat.primitives.kdf',
    'cryptography.hazmat.primitives.serialization',
    'cryptography.x509',
    
    # HTTP and WebSocket
    'httpx',
    'httpx._client',
    'httpx._config',
    'httpx._transports',
    'httpx._api',
    'websockets',
    'websockets.client',
    'websockets.server',
    'websockets.protocol',
    'websockets.frames',
    'websockets.exceptions',
    'aiofiles',
    'aiofiles.threadpool',
    'aiofiles.threadpool.binary',
    'aiofiles.threadpool.text',
    
    # Logging and monitoring
    'structlog',
    'structlog.stdlib',
    'structlog.processors',
    'structlog.contextvars',
    'pythonjsonlogger',
    'pythonjsonlogger.jsonlogger',
    'sentry_sdk',
    'sentry_sdk.integrations',
    'sentry_sdk.integrations.fastapi',
    'sentry_sdk.integrations.starlette',
    'sentry_sdk.integrations.sqlalchemy',
    'sentry_sdk.integrations.celery',
    'sentry_sdk.integrations.redis',
    'prometheus_client',
    'prometheus_client.core',
    'prometheus_client.registry',
    'prometheus_client.metrics',
    'prometheus_client.exposition',
    
    # Utilities
    'email_validator',
    'dateutil',
    'dateutil.parser',
    'dateutil.tz',
    'dateutil.relativedelta',
    'ujson',
    'psutil',
    'watchfiles',
    'watchfiles.main',
    'watchfiles.watch',
    
    # OpenMDAO and optimization
    'openmdao',
    'openmdao.api',
    'openmdao.core',
    'openmdao.drivers',
    'openmdao.solvers',
    'openmdao.components',
    'openmdao.utils',
    'nevergrad',
    'nevergrad.optimization',
    'nevergrad.parametrization',
    'nevergrad.common',
    
    # Standard library modules that might be missed
    'multiprocessing',
    'multiprocessing.pool',
    'multiprocessing.process',
    'multiprocessing.queues',
    'multiprocessing.synchronize',
    'multiprocessing.sharedctypes',
    'multiprocessing.heap',
    'multiprocessing.util',
    'concurrent.futures',
    'concurrent.futures.thread',
    'concurrent.futures.process',
    'asyncio',
    'asyncio.events',
    'asyncio.tasks',
    'asyncio.streams',
    'asyncio.subprocess',
    'asyncio.windows_utils',
    'ssl',
    'ssl._ssl',
    'json',
    'json.decoder',
    'json.encoder',
    'json.scanner',
    'decimal',
    'fractions',
    'numbers',
    'collections',
    'collections.abc',
    'itertools',
    'functools',
    'operator',
    'pathlib',
    'os',
    'sys',
    'time',
    'datetime',
    'typing',
    'typing_extensions',
    'dataclasses',
    'enum',
    'uuid',
    'hashlib',
    'hmac',
    'secrets',
    'base64',
    'binascii',
    'urllib.parse',
    'urllib.request',
    'urllib.response',
    'urllib.error',
    'http',
    'http.client',
    'http.server',
    'email',
    'email.message',
    'email.mime',
    'email.mime.text',
    'email.mime.multipart',
    'email.mime.base',
    'email.encoders',
    'email.utils',
    'mimetypes',
    'socket',
    'socketserver',
    'selectors',
    'select',
    'signal',
    'threading',
    'queue',
    'weakref',
    'copy',
    'pickle',
    'shelve',
    'dbm',
    'sqlite3',
    'csv',
    'configparser',
    'argparse',
    'textwrap',
    'string',
    're',
    'math',
    'statistics',
    'random',
    'secrets',
    'inspect',
    'importlib',
    'importlib.util',
    'importlib.machinery',
    'importlib.metadata',
    'importlib.resources',
    'pkgutil',
    'runpy',
    'site',
    'platform',
    'subprocess',
    'shutil',
    'tempfile',
    'glob',
    'fnmatch',
    'linecache',
    'traceback',
    'warnings',
    'contextlib',
    'abc',
    'types',
    'builtins',
    'io',
    'io.io',
    'io.text',
    'io.buffered',
    'io.raw',
]

# Exclude modules that are not needed or cause issues
excluded_modules = [
    'tkinter',
    'tkinter.ttk',
    'tkinter.filedialog',
    'tkinter.messagebox',
    'tkinter.colorchooser',
    'tkinter.font',
    'tkinter.scrolledtext',
    'tkinter.dnd',
    'tkinter.tix',
    'tkinter.simpledialog',
    'tkinter.commondialog',
    'matplotlib',
    'matplotlib.pyplot',
    'matplotlib.backends',
    'matplotlib.backends.backend_tkagg',
    'matplotlib.backends.backend_agg',
    'matplotlib.backends.backend_cairo',
    'matplotlib.backends.backend_pdf',
    'matplotlib.backends.backend_svg',
    'matplotlib.backends.backend_ps',
    'matplotlib.backends.backend_pgf',
    'IPython',
    'IPython.core',
    'IPython.terminal',
    'jupyter',
    'jupyter_client',
    'jupyter_core',
    'notebook',
    'nbformat',
    'nbconvert',
    'ipykernel',
    'ipython_genutils',
    'traitlets',
    'decorator',
    'backcall',
    'prompt_toolkit',
    'pygments',
    'sphinx',
    'docutils',
    'pytest',
    'pytest_asyncio',
    'pytest_cov',
    'faker',
    'hypothesis',
    'coverage',
    'tox',
    'setuptools',
    'pip',
    'wheel',
    'virtualenv',
    'pipenv',
    'poetry',
    'conda',
    'mypy',
    'pylint',
    'flake8',
    'black',
    'isort',
    'bandit',
    'safety',
    'pre_commit',
    'twine',
    'build',
    'hatch',
    'flit',
    'pdm',
]

a = Analysis(
    [str(backend_dir / "main.py")],
    pathex=[str(backend_dir)],
    binaries=[],
    datas=backend_files,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excluded_modules,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

# Filter out unnecessary binaries
a.binaries = [b for b in a.binaries if not any(excl in b[0] for excl in [
    'tkinter', 'matplotlib', 'IPython', 'jupyter', 'notebook', 'nbformat',
    'nbconvert', 'ipykernel', 'ipython_genutils', 'traitlets', 'decorator',
    'backcall', 'prompt_toolkit', 'pygments', 'sphinx', 'docutils',
    'pytest', 'faker', 'hypothesis', 'coverage', 'tox', 'setuptools',
    'pip', 'wheel', 'virtualenv', 'pipenv', 'poetry', 'conda', 'mypy',
    'pylint', 'flake8', 'black', 'isort', 'bandit', 'safety', 'pre_commit',
    'twine', 'build', 'hatch', 'flit', 'pdm',
])]

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='cfd-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_hook=[],
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)