//! Backend Process Manager
//!
//! Manages the lifecycle of the Python FastAPI backend process.

use anyhow::{Context, Result};
use std::ffi::OsString;
use std::path::{Path, PathBuf};
use std::process::{Command as StdCommand, Stdio};
use std::sync::Arc;
use std::time::Duration;
use tauri::{AppHandle, Emitter, Manager};
use tokio::io::{AsyncBufReadExt, AsyncRead, BufReader};
use tokio::process::{Child, Command};
use tokio::sync::{Mutex, RwLock};
use tokio::time::timeout;

/// Backend process state
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum BackendStatus {
    Stopped,
    Starting,
    Running,
    Stopping,
    Error(String),
}

/// Backend log entry
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct BackendLog {
    pub timestamp: String,
    pub level: String,
    pub message: String,
}

/// A fully local Python runtime staged into a release bundle.
///
/// The `venv` contains the engineering packages while `python` contains the
/// base CPython files that a Windows virtual environment otherwise references
/// from the build machine.  Keeping this explicit avoids any dependency on a
/// Python installation on an engineer's workstation.
#[derive(Debug, Clone)]
struct BundledPythonRuntime {
    python: PathBuf,
    bootstrap: PathBuf,
    site_packages: PathBuf,
    path_prefixes: Vec<PathBuf>,
}

/// Process launch data kept separate from discovery so a sidecar and managed
/// source runtime can share the same lifecycle, health checks and private API.
struct BackendLaunchSpec {
    program: PathBuf,
    args: Vec<OsString>,
    working_directory: PathBuf,
    python_paths: Vec<PathBuf>,
    python_home: Option<PathBuf>,
    path_prefixes: Vec<PathBuf>,
}

/// Backend manager handles the Python backend process lifecycle
#[derive(Clone)]
pub struct BackendManager {
    process: Arc<Mutex<Option<Child>>>,
    status: Arc<RwLock<BackendStatus>>,
    logs: Arc<RwLock<Vec<BackendLog>>>,
    backend_path: Arc<RwLock<Option<PathBuf>>>,
    python_path: Arc<RwLock<Option<PathBuf>>>,
    endpoint: Arc<RwLock<Option<String>>>,
    api_token: Arc<RwLock<Option<String>>>,
    startup_lock: Arc<Mutex<()>>,
    max_logs: usize,
}

impl BackendManager {
    /// Create a new backend manager
    pub fn new() -> Self {
        Self {
            process: Arc::new(Mutex::new(None)),
            status: Arc::new(RwLock::new(BackendStatus::Stopped)),
            logs: Arc::new(RwLock::new(Vec::new())),
            backend_path: Arc::new(RwLock::new(None)),
            python_path: Arc::new(RwLock::new(None)),
            endpoint: Arc::new(RwLock::new(None)),
            api_token: Arc::new(RwLock::new(None)),
            startup_lock: Arc::new(Mutex::new(())),
            max_logs: 1000,
        }
    }

    /// Get the current backend status
    pub async fn status(&self) -> BackendStatus {
        self.status.read().await.clone()
    }

    /// Get backend logs
    pub async fn logs(&self) -> Vec<BackendLog> {
        self.logs.read().await.clone()
    }

    /// Add a log entry
    async fn add_log(&self, level: &str, message: &str) {
        let log = BackendLog {
            timestamp: chrono::Utc::now().to_rfc3339(),
            level: level.to_string(),
            message: message.to_string(),
        };
        let mut logs = self.logs.write().await;
        logs.push(log);
        if logs.len() > self.max_logs {
            let excess = logs.len() - self.max_logs;
            logs.drain(0..excess);
        }
    }

    /// Emit status change to frontend
    async fn emit_status(&self, app: &AppHandle, status: BackendStatus) {
        let _ = app.emit("backend-status-changed", &status);
    }

    /// Find the backend executable
    async fn find_backend(&self, app: &AppHandle) -> Result<PathBuf> {
        // Check if we already have a cached path
        if let Some(path) = self.backend_path.read().await.as_ref() {
            if path.exists() {
                return Ok(path.clone());
            }
        }

        // Try to find the backend in various locations
        let resource_dir = app
            .path()
            .resource_dir()
            .context("Failed to get resource directory")?;

        let packaged_sidecar_paths = vec![
            resource_dir.join("bin/backend/cfd-backend"),
            resource_dir.join("bin/backend/cfd-backend.exe"),
            // Tauri bundles resources beneath `resources` on some Windows
            // layouts, while the standalone Inno installer places them beside
            // the executable. Support both without exposing a Python command
            // to the engineer.
            resource_dir.join("resources/bin/backend/cfd-backend"),
            resource_dir.join("resources/bin/backend/cfd-backend.exe"),
        ];
        // The managed Python fallback is generated by build.rs.  Prefer it in
        // release builds so an old or partially frozen sidecar can never
        // prevent HX CFD from starting its real local backend.
        let bundled_runtime_paths = vec![
            resource_dir.join("bin/backend-runtime/backend/src/cfd_backend/main.py"),
            resource_dir.join("resources/bin/backend-runtime/backend/src/cfd_backend/main.py"),
            resource_dir.join("backend-runtime/backend/src/cfd_backend/main.py"),
        ];
        // Tauri's development working directory is chosen by the launcher and
        // is not a stable application contract. Resolve the editable backend
        // from the Rust package instead of relying on a relative path.
        let development_paths = vec![PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("backend")
            .join("src")
            .join("cfd_backend")
            .join("main.py")];
        // A debug run uses the editable backend source.  Release uses the
        // bundled managed runtime before any sidecar; both remain completely
        // private to Tauri and never expose a Python command to the engineer.
        let possible_paths = if cfg!(debug_assertions) {
            development_paths
                .into_iter()
                .chain(bundled_runtime_paths.into_iter())
                .chain(packaged_sidecar_paths.into_iter())
                .collect::<Vec<_>>()
        } else {
            bundled_runtime_paths
                .into_iter()
                .chain(packaged_sidecar_paths.into_iter())
                .collect::<Vec<_>>()
        };

        for path in possible_paths {
            if path.exists() {
                let canonical = path.canonicalize().unwrap_or(path);
                *self.backend_path.write().await = Some(canonical.clone());
                return Ok(canonical);
            }
        }

        anyhow::bail!("Backend not found. Please build the backend first.")
    }

    /// Find Python executable
    async fn find_python(&self) -> Result<PathBuf> {
        if let Some(path) = self.python_path.read().await.as_ref() {
            if path.exists() {
                return Ok(path.clone());
            }
        }

        // Development runs use an isolated project runtime. This prevents the
        // desktop shell from accidentally selecting an unrelated Python from
        // PATH (for example the one used by an editor), which would start and
        // immediately fail with missing CFD dependencies.
        let managed_runtime = if cfg!(target_os = "windows") {
            PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .join("backend")
                .join(".venv")
                .join("Scripts")
                .join("python.exe")
        } else {
            PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .join("backend")
                .join(".venv")
                .join("bin")
                .join("python")
        };
        if managed_runtime.exists() {
            *self.python_path.write().await = Some(managed_runtime.clone());
            return Ok(managed_runtime);
        }

        // Try common Python commands
        let python_commands = if cfg!(target_os = "windows") {
            vec!["python.exe", "python3.exe", "python"]
        } else {
            vec!["python3", "python"]
        };

        for cmd in python_commands {
            if let Ok(output) = StdCommand::new(cmd).arg("--version").output() {
                if output.status.success() {
                    let path = PathBuf::from(cmd);
                    *self.python_path.write().await = Some(path.clone());
                    return Ok(path);
                }
            }
        }

        anyhow::bail!("The managed local Python runtime is not ready. Repair it from HX CFD Settings → Engines.")
    }

    fn bundled_python_runtime(backend_path: &Path) -> Option<BundledPythonRuntime> {
        let source_root = backend_path.parent()?.parent()?;
        let backend_root = source_root.parent()?;
        let root = backend_root.parent()?.to_path_buf();
        if !root.join("HX_CFD_RUNTIME").is_file() {
            return None;
        }

        let python_root = root.join("python");
        let python = if cfg!(target_os = "windows") {
            python_root.join("python.exe")
        } else {
            python_root.join("bin/python3")
        };
        let site_packages = if cfg!(target_os = "windows") {
            root.join("venv/Lib/site-packages")
        } else {
            root.join("venv/lib/python3.11/site-packages")
        };
        let bootstrap = root.join("launch_backend.py");
        if !python.is_file() || !site_packages.is_dir() || !bootstrap.is_file() {
            return None;
        }

        let mut path_prefixes = vec![python_root];
        let scripts = if cfg!(target_os = "windows") {
            root.join("venv/Scripts")
        } else {
            root.join("venv/bin")
        };
        if scripts.is_dir() {
            path_prefixes.push(scripts);
        }

        Some(BundledPythonRuntime {
            python,
            bootstrap,
            site_packages,
            path_prefixes,
        })
    }

    fn launch_spec(backend_path: &Path, python_path: Option<&Path>) -> Result<BackendLaunchSpec> {
        if backend_path
            .extension()
            .map_or(false, |extension| extension == "exe")
        {
            let working_directory = backend_path
                .parent()
                .unwrap_or_else(|| Path::new("."))
                .to_path_buf();
            return Ok(BackendLaunchSpec {
                program: backend_path.to_path_buf(),
                args: Vec::new(),
                working_directory,
                python_paths: Vec::new(),
                python_home: None,
                path_prefixes: Vec::new(),
            });
        }

        if backend_path
            .extension()
            .map_or(false, |extension| extension == "py")
        {
            let source_root = backend_path
                .parent()
                .and_then(Path::parent)
                .context("Backend source root is invalid.")?
                .to_path_buf();
            if let Some(runtime) = Self::bundled_python_runtime(backend_path) {
                let python_home = runtime
                    .python
                    .parent()
                    .context("Bundled Python executable has no parent directory")?
                    .to_path_buf();
                return Ok(BackendLaunchSpec {
                    program: runtime.python,
                    args: vec![runtime.bootstrap.into_os_string()],
                    working_directory: source_root.clone(),
                    python_paths: vec![source_root, runtime.site_packages],
                    python_home: Some(python_home),
                    path_prefixes: runtime.path_prefixes,
                });
            }

            let python_path =
                python_path.context("Python runtime is required for the development backend.")?;
            return Ok(BackendLaunchSpec {
                program: python_path.to_path_buf(),
                args: vec![backend_path.as_os_str().to_os_string()],
                working_directory: source_root.clone(),
                python_paths: vec![source_root],
                python_home: None,
                path_prefixes: Vec::new(),
            });
        }

        anyhow::bail!("Unknown backend type: {}", backend_path.display())
    }

    /// Start the backend process and surface a useful state if startup fails.
    pub async fn start(&self, app: &AppHandle) -> Result<()> {
        // Several React surfaces may become ready at the same time. Serialize
        // their start requests so only one managed FastAPI process owns the
        // project database and loopback endpoint.
        let _startup_guard = self.startup_lock.lock().await;

        // Check if already running
        if matches!(self.status().await, BackendStatus::Running) {
            self.add_log("info", "Backend already running").await;
            return Ok(());
        }

        // Update status to starting
        *self.status.write().await = BackendStatus::Starting;
        self.emit_status(app, BackendStatus::Starting).await;
        self.add_log("info", "Starting backend...").await;

        let result = self.start_inner(app).await;
        if let Err(error) = result.as_ref() {
            let message = format!("Backend startup failed: {error:#}");
            *self.status.write().await = BackendStatus::Error(message.clone());
            *self.endpoint.write().await = None;
            *self.api_token.write().await = None;
            self.add_log("error", &message).await;
            self.emit_status(app, BackendStatus::Error(message)).await;
        }

        result
    }

    /// Start the backend and wait until the private loopback service is healthy.
    async fn start_inner(&self, app: &AppHandle) -> Result<()> {
        // Discover the backend before selecting a Python interpreter.  A
        // release resource may provide its own CPython runtime, while the
        // editable development source uses the managed project environment.
        let backend_path = self.find_backend(app).await?;
        let uses_bundled_runtime = Self::bundled_python_runtime(&backend_path).is_some();
        let python_path = if backend_path
            .extension()
            .map_or(false, |extension| extension == "py")
            && !uses_bundled_runtime
        {
            Some(self.find_python().await?)
        } else {
            None
        };

        self.add_log("info", &format!("Backend path: {}", backend_path.display()))
            .await;
        if let Some(python_path) = &python_path {
            self.add_log("info", &format!("Python path: {}", python_path.display()))
                .await;
        } else if uses_bundled_runtime {
            self.add_log("info", "Using the bundled managed Python runtime")
                .await;
        }

        let launch = Self::launch_spec(&backend_path, python_path.as_deref())?;
        let port = reserve_loopback_port()?;
        let app_data_dir = app
            .path()
            .app_data_dir()
            .context("Failed to get app data directory")?;
        let data_dir = app_data_dir.join("data");
        let database_url = local_sqlite_database_url(&data_dir)?;
        // The token is intentionally per-process and is never returned to the
        // webview. It protects this otherwise private loopback API from other
        // local processes which might discover the ephemeral port.
        let api_token = uuid::Uuid::new_v4().simple().to_string();

        // The FastAPI service is strictly local and its ephemeral address never
        // crosses into the webview. Tauri exposes typed commands instead.
        let python_paths = if launch.python_paths.is_empty() {
            None
        } else {
            Some(
                std::env::join_paths(&launch.python_paths)
                    .context("Unable to construct the managed Python module path")?,
            )
        };
        let runtime_path = if launch.path_prefixes.is_empty() {
            None
        } else {
            let mut entries = launch.path_prefixes.clone();
            if let Some(inherited) = std::env::var_os("PATH") {
                entries.extend(std::env::split_paths(&inherited));
            }
            Some(
                std::env::join_paths(entries)
                    .context("Unable to construct the bundled Python executable path")?,
            )
        };

        // The FastAPI service is strictly local and its ephemeral address never
        // crosses into the webview. Tauri exposes typed commands instead.
        let mut command = Command::new(&launch.program);
        command
            .args(&launch.args)
            .current_dir(&launch.working_directory)
            .env("PYTHONUNBUFFERED", "1")
            .env("CFD_PLATFORM_TAURI", "1")
            .env("CFD_PLATFORM_TAURI_TOKEN", &api_token)
            .env("HOST", "127.0.0.1")
            .env("PORT", port.to_string())
            .env("DATA_DIR", &data_dir)
            .env("DATABASE_URL", &database_url)
            .env("LOGS_DIR", app_data_dir.join("logs"))
            .env("PROJECTS_DIR", app_data_dir.join("projects"))
            .env("TEMP_DIR", app_data_dir.join("tmp"))
            .env("CACHE_DIR", app_data_dir.join("cache"))
            .stdout(Stdio::piped())
            .stderr(Stdio::piped());
        if let Some(python_paths) = python_paths {
            command
                .env("PYTHONPATH", python_paths)
                .env("PYTHONNOUSERSITE", "1");
        }
        if let Some(python_home) = &launch.python_home {
            command.env("PYTHONHOME", python_home);
        } else {
            // Do not let an unrelated shell-level PYTHONHOME poison a managed
            // venv or frozen sidecar.
            command.env_remove("PYTHONHOME");
        }
        if let Some(runtime_path) = runtime_path {
            command.env("PATH", runtime_path);
        }

        let mut child = command.spawn().context("Failed to spawn backend process")?;

        // Take stdout and stderr
        let stdout = child.stdout.take().context("Failed to capture stdout")?;
        let stderr = child.stderr.take().context("Failed to capture stderr")?;

        let app_handle = app.clone();

        // Store the process
        *self.process.lock().await = Some(child);
        *self.endpoint.write().await = Some(format!("http://127.0.0.1:{}", port));
        *self.api_token.write().await = Some(api_token);

        // Spawn log readers
        let stdout_reader = self.spawn_log_reader(stdout, "stdout", app_handle.clone());
        let stderr_reader = self.spawn_log_reader(stderr, "stderr", app_handle.clone());

        // A successful OS spawn is not enough: FastAPI can still fail during
        // its lifespan (for example because the local database cannot open).
        // Keep the desktop in Starting until the private endpoint responds.
        if let Err(error) = self.wait_for_startup_health().await {
            let _ = self.stop().await;
            let _ = tokio::join!(stdout_reader, stderr_reader);
            return Err(error);
        }

        // Update status only after FastAPI has completed startup.
        *self.status.write().await = BackendStatus::Running;
        self.emit_status(app, BackendStatus::Running).await;
        self.add_log("info", "Backend started successfully").await;

        let monitor = self.clone();
        tokio::spawn(async move {
            monitor
                .monitor_process(app_handle, stdout_reader, stderr_reader)
                .await;
        });

        Ok(())
    }

    /// Wait for FastAPI startup while also detecting an early child-process exit.
    async fn wait_for_startup_health(&self) -> Result<()> {
        let deadline = tokio::time::Instant::now() + Duration::from_secs(15);

        loop {
            if self.probe_health(Duration::from_millis(500)).await {
                return Ok(());
            }

            let exited = {
                let mut process_guard = self.process.lock().await;
                match process_guard.as_mut() {
                    Some(process) => match process.try_wait() {
                        Ok(Some(status)) => {
                            *process_guard = None;
                            Some(Ok(status))
                        }
                        Ok(None) => None,
                        Err(error) => {
                            *process_guard = None;
                            Some(Err(error))
                        }
                    },
                    None => Some(Err(std::io::Error::new(
                        std::io::ErrorKind::NotFound,
                        "Backend process was not available during startup",
                    ))),
                }
            };

            if let Some(exit_status) = exited {
                match exit_status {
                    Ok(status) => anyhow::bail!(
                        "Backend exited before its health endpoint became available ({status})"
                    ),
                    Err(error) => anyhow::bail!(
                        "Unable to inspect the backend process during startup: {error}"
                    ),
                }
            }

            if tokio::time::Instant::now() >= deadline {
                anyhow::bail!("Backend did not become healthy within 15 seconds")
            }

            tokio::time::sleep(Duration::from_millis(125)).await;
        }
    }

    async fn monitor_process(
        &self,
        app: AppHandle,
        stdout_reader: tokio::task::JoinHandle<()>,
        stderr_reader: tokio::task::JoinHandle<()>,
    ) {
        loop {
            tokio::time::sleep(Duration::from_millis(250)).await;
            let exit_status = {
                let mut process_guard = self.process.lock().await;
                match process_guard.as_mut() {
                    Some(process) => match process.try_wait() {
                        Ok(Some(status)) => {
                            *process_guard = None;
                            Some(Ok(status))
                        }
                        Ok(None) => None,
                        Err(error) => {
                            *process_guard = None;
                            Some(Err(error))
                        }
                    },
                    None => return,
                }
            };

            if let Some(exit_status) = exit_status {
                let _ = tokio::join!(stdout_reader, stderr_reader);
                let final_status = match exit_status {
                    Ok(status) if status.success() => BackendStatus::Stopped,
                    Ok(status) => {
                        BackendStatus::Error(format!("Backend exited with code: {}", status))
                    }
                    Err(error) => BackendStatus::Error(format!("Backend process error: {}", error)),
                };
                *self.status.write().await = final_status.clone();
                *self.endpoint.write().await = None;
                *self.api_token.write().await = None;
                self.emit_status(&app, final_status).await;
                self.add_log("info", "Backend stopped").await;
                return;
            }
        }
    }

    /// Spawn a log reader for stdout/stderr
    fn spawn_log_reader<R>(
        &self,
        stream: R,
        stream_name: &str,
        app: AppHandle,
    ) -> tokio::task::JoinHandle<()>
    where
        R: AsyncRead + Unpin + Send + 'static,
    {
        let logs = self.logs.clone();
        let stream_name = stream_name.to_string();
        let app_handle = app.clone();

        tokio::spawn(async move {
            let reader = BufReader::new(stream);
            let mut lines = reader.lines();

            while let Ok(Some(line)) = lines.next_line().await {
                let level = if stream_name == "stderr" {
                    "error"
                } else {
                    "info"
                };
                let log = BackendLog {
                    timestamp: chrono::Utc::now().to_rfc3339(),
                    level: level.to_string(),
                    message: line,
                };

                let mut logs_guard = logs.write().await;
                logs_guard.push(log.clone());
                if logs_guard.len() > 1000 {
                    let excess = logs_guard.len() - 1000;
                    logs_guard.drain(0..excess);
                }

                let _ = app_handle.emit("backend-log", &log);
            }
        })
    }

    /// Stop the backend process
    pub async fn stop(&self) -> Result<()> {
        let mut process_guard = self.process.lock().await;
        if let Some(mut child) = process_guard.take() {
            *self.status.write().await = BackendStatus::Stopping;
            self.add_log("info", "Stopping backend...").await;

            // Try graceful shutdown first
            #[cfg(unix)]
            {
                use tokio::signal::unix::{signal, SignalKind};
                let _ = child.kill().await;
            }
            #[cfg(windows)]
            {
                // CFD workers may create child solver processes. Stop the
                // complete local process tree so they cannot outlive HX CFD.
                if let Some(pid) = child.id() {
                    let _ = StdCommand::new("taskkill")
                        .args(["/PID", &pid.to_string(), "/T", "/F"])
                        .output();
                } else {
                    let _ = child.kill().await;
                }
            }

            // Wait for process to exit with timeout
            match timeout(Duration::from_secs(10), child.wait()).await {
                Ok(Ok(status)) => {
                    self.add_log("info", &format!("Backend stopped with status: {}", status))
                        .await;
                }
                Ok(Err(e)) => {
                    self.add_log("error", &format!("Error waiting for backend: {}", e))
                        .await;
                }
                Err(_) => {
                    self.add_log("warn", "Backend stop timeout, force killing")
                        .await;
                    let _ = child.kill().await;
                }
            }
        }

        *self.status.write().await = BackendStatus::Stopped;
        *self.endpoint.write().await = None;
        *self.api_token.write().await = None;
        Ok(())
    }

    /// Restart the backend
    pub async fn restart(&self, app: &AppHandle) -> Result<()> {
        self.stop().await?;
        tokio::time::sleep(Duration::from_secs(1)).await;
        self.start(app).await
    }

    /// Call the managed FastAPI workflow service from the trusted Tauri side.
    ///
    /// The webview never receives the endpoint or token.  This is the single
    /// desktop execution path: React invokes a Tauri command, Rust calls the
    /// long-lived local API, then the Python workflow service selects adapters.
    async fn call_private_api(
        &self,
        app: &AppHandle,
        method: reqwest::Method,
        path: &str,
        payload: Option<&serde_json::Value>,
        request_timeout: Duration,
    ) -> Result<serde_json::Value> {
        self.start(app).await?;

        let endpoint = self
            .endpoint
            .read()
            .await
            .clone()
            .context("The managed backend did not publish a loopback endpoint")?;
        let api_token = self
            .api_token
            .read()
            .await
            .clone()
            .context("The managed backend did not publish a desktop session token")?;
        let method_label = method.as_str().to_string();
        let url = format!("{endpoint}{path}");
        let client = reqwest::Client::builder()
            .connect_timeout(Duration::from_secs(5))
            .build()
            .context("Unable to create the private backend API client")?;
        let mut request = client
            .request(method, &url)
            .bearer_auth(api_token)
            .timeout(request_timeout);
        if let Some(payload) = payload {
            request = request.json(payload);
        }

        let response = request
            .send()
            .await
            .with_context(|| format!("Local backend API request failed: {method_label} {path}"))?;
        let status = response.status();
        let body = response
            .text()
            .await
            .context("Unable to read the local backend API response")?;
        if !status.is_success() {
            let detail = serde_json::from_str::<serde_json::Value>(&body)
                .ok()
                .and_then(|value| value.get("detail").cloned())
                .and_then(|value| value.as_str().map(str::to_owned))
                .filter(|value| !value.is_empty())
                .unwrap_or(body);
            anyhow::bail!(
                "Local backend API {method_label} {path} failed with HTTP {}: {detail}",
                status
            );
        }
        if body.trim().is_empty() {
            return Ok(serde_json::Value::Null);
        }
        serde_json::from_str(&body).context("Local backend API returned invalid JSON")
    }

    /// Query capability state for the fourteen local implementation engines.
    pub async fn engine_inventory(&self, app: &AppHandle) -> Result<serde_json::Value> {
        self.call_private_api(
            app,
            reqwest::Method::GET,
            "/api/v1/workflow/engines?refresh=true",
            None,
            Duration::from_secs(30),
        )
        .await
    }

    /// List durable local projects without opening a network endpoint.
    pub async fn list_local_projects(&self, app: &AppHandle) -> Result<serde_json::Value> {
        self.call_private_api(
            app,
            reqwest::Method::GET,
            "/api/v1/workflow/projects",
            None,
            Duration::from_secs(30),
        )
        .await
    }

    /// Create a new initialized project through the Python workflow service.
    pub async fn create_local_project(
        &self,
        app: &AppHandle,
        project_id: &str,
    ) -> Result<serde_json::Value> {
        self.call_private_api(
            app,
            reqwest::Method::POST,
            "/api/v1/workflow/projects",
            Some(&serde_json::json!({ "project_id": project_id })),
            Duration::from_secs(30),
        )
        .await
    }

    /// Open an existing local project without silently creating a directory.
    pub async fn open_local_project(
        &self,
        app: &AppHandle,
        project_id: &str,
    ) -> Result<serde_json::Value> {
        self.call_private_api(
            app,
            reqwest::Method::POST,
            &format!("/api/v1/workflow/projects/{project_id}/open"),
            None,
            Duration::from_secs(30),
        )
        .await
    }

    /// Rename a validated local project and its manifest.
    pub async fn rename_local_project(
        &self,
        app: &AppHandle,
        project_id: &str,
        new_project_id: &str,
    ) -> Result<serde_json::Value> {
        self.call_private_api(
            app,
            reqwest::Method::PATCH,
            &format!("/api/v1/workflow/projects/{project_id}"),
            Some(&serde_json::json!({ "new_project_id": new_project_id })),
            Duration::from_secs(30),
        )
        .await
    }

    /// Archive an active project while retaining its local data.
    pub async fn archive_local_project(
        &self,
        app: &AppHandle,
        project_id: &str,
    ) -> Result<serde_json::Value> {
        self.call_private_api(
            app,
            reqwest::Method::POST,
            &format!("/api/v1/workflow/projects/{project_id}/archive"),
            None,
            Duration::from_secs(30),
        )
        .await
    }

    /// Permanently delete one validated project from the local project store.
    pub async fn delete_local_project(
        &self,
        app: &AppHandle,
        project_id: &str,
    ) -> Result<serde_json::Value> {
        self.call_private_api(
            app,
            reqwest::Method::DELETE,
            &format!("/api/v1/workflow/projects/{project_id}"),
            None,
            Duration::from_secs(30),
        )
        .await
    }

    /// Read durable workflow state for a project through the private desktop bridge.
    pub async fn workflow_snapshot(
        &self,
        app: &AppHandle,
        project_id: &str,
    ) -> Result<serde_json::Value> {
        self.call_private_api(
            app,
            reqwest::Method::GET,
            &format!("/api/v1/workflow/projects/{project_id}"),
            None,
            Duration::from_secs(30),
        )
        .await
    }

    /// List opaque project artifact descriptors through the local workflow service.
    pub async fn workflow_artifacts(
        &self,
        app: &AppHandle,
        project_id: &str,
        stage_id: Option<&str>,
    ) -> Result<serde_json::Value> {
        let path = match stage_id {
            Some(stage_id) => {
                format!("/api/v1/workflow/projects/{project_id}/artifacts?stage_id={stage_id}")
            }
            None => format!("/api/v1/workflow/projects/{project_id}/artifacts"),
        };
        self.call_private_api(
            app,
            reqwest::Method::GET,
            &path,
            None,
            Duration::from_secs(30),
        )
        .await
    }

    /// Read one bounded local artifact by its opaque workflow catalog ID.
    pub async fn read_workflow_artifact(
        &self,
        app: &AppHandle,
        project_id: &str,
        artifact_id: &str,
    ) -> Result<serde_json::Value> {
        self.call_private_api(
            app,
            reqwest::Method::GET,
            &format!("/api/v1/workflow/projects/{project_id}/artifacts/{artifact_id}"),
            None,
            Duration::from_secs(30),
        )
        .await
    }

    /// Export one project-owned artifact after the webview obtains a native save path.
    pub async fn export_workflow_artifact(
        &self,
        app: &AppHandle,
        project_id: &str,
        artifact_id: &str,
        destination: &str,
    ) -> Result<serde_json::Value> {
        self.call_private_api(
            app,
            reqwest::Method::POST,
            &format!("/api/v1/workflow/projects/{project_id}/artifacts/{artifact_id}/export"),
            Some(&serde_json::json!({ "destination": destination })),
            Duration::from_secs(30),
        )
        .await
    }

    /// Persist a semantic stage recipe using the same local service contract as FastAPI.
    pub async fn configure_workflow_stage(
        &self,
        app: &AppHandle,
        project_id: &str,
        stage_id: &str,
        recipe: &serde_json::Value,
    ) -> Result<serde_json::Value> {
        self.call_private_api(
            app,
            reqwest::Method::PUT,
            &format!("/api/v1/workflow/projects/{project_id}/stages/{stage_id}"),
            Some(&serde_json::json!({ "configuration": recipe })),
            Duration::from_secs(30),
        )
        .await
    }

    /// Execute a configured stage using the backend's real local engine adapter.
    pub async fn execute_workflow_stage(
        &self,
        app: &AppHandle,
        project_id: &str,
        stage_id: &str,
        recipe: Option<&serde_json::Value>,
    ) -> Result<serde_json::Value> {
        self.call_private_api(
            app,
            reqwest::Method::POST,
            &format!("/api/v1/workflow/projects/{project_id}/stages/{stage_id}/execute"),
            Some(&serde_json::json!({ "recipe": recipe })),
            // A solver may legitimately run for two hours.  The UI remains
            // responsive because this awaits in Tauri's async command, not in
            // the render process, and the backend owns durable job evidence.
            Duration::from_secs(7_500),
        )
        .await
    }

    /// Check backend health via the private loopback endpoint selected at launch.
    pub async fn health_check(&self) -> Result<bool> {
        Ok(self.probe_health(Duration::from_secs(5)).await)
    }

    /// Probe the private FastAPI endpoint without exposing it to the webview.
    async fn probe_health(&self, request_timeout: Duration) -> bool {
        let endpoint = match self.endpoint.read().await.clone() {
            Some(endpoint) => endpoint,
            None => return false,
        };
        let client = reqwest::Client::new();
        let response = client
            .get(format!("{}/health", endpoint))
            .timeout(request_timeout)
            .send()
            .await;

        match response {
            Ok(resp) => resp.status().is_success(),
            Err(_) => false,
        }
    }
}

impl Default for BackendManager {
    fn default() -> Self {
        Self::new()
    }
}

fn reserve_loopback_port() -> Result<u16> {
    let listener = std::net::TcpListener::bind("127.0.0.1:0")
        .context("Unable to reserve a private loopback port for the backend")?;
    let port = listener
        .local_addr()
        .context("Unable to inspect the private loopback port")?
        .port();
    drop(listener);
    Ok(port)
}

/// Build a SQLite URL that remains valid when the desktop changes its working
/// directory. SQLAlchemy accepts Windows drive paths when their separators are
/// normalized to forward slashes.
fn local_sqlite_database_url(data_dir: &Path) -> Result<String> {
    std::fs::create_dir_all(data_dir).with_context(|| {
        format!(
            "Unable to create the local backend data directory: {}",
            data_dir.display()
        )
    })?;
    let database_path = data_dir.join("cfd.db");
    let url_path = database_path.to_string_lossy().replace('\\', "/");
    Ok(format!("sqlite+aiosqlite:///{}", url_path))
}
